version: '3.8'

services:
    nginx:
        container_name: papers-nginx
        image: nginx:latest
        ports:
            - "8080:8080"
            - "8443:8443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ../../papers-web/dist:/usr/share/nginx/html
        depends_on:
            - server
    db:
        container_name: papers-mssql
        image: "mcr.microsoft.com/mssql/server"
        env_file: 
            - db.env
        ports:
            - "1433:1433"
        volumes:
            - ${DB_VOLUME_PATH}:/var/opt/mssql/data
    server:
        container_name: papers-server
        image: papers-server:0.0.34.2
        volumes:
            - ${CONFIG_FILE_PATH}:/app/appsettings.json
        ports:
            - "759:80"
            - "8442:443"
        depends_on:
            - db