trigger: none

stages:
- stage: Backend_build
  pool:
    name: Backend-build
  jobs:
  - job: build
    steps:
    - powershell: |
        write-host 'build 123'
      displayName: 'Run build'
  - job: 
    displayName: UI tests
    steps:
    - powershell: |
        write-host 'build 321'
      displayName: 'Run tests'

- stage: Dev
  dependsOn:
  - Backend_build
  jobs:
  - deployment:
    displayName: Dev deploy
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: write-host 'test depl'
             displayName: 'Dev based stage'
